### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Rubel-hossain** [kingRayhan/LineProgressbar#1]
This plugin is pretty well and I have some feature request. 
Some Points:

* This plugin should be make actionable by class name.
* All option can be control from html markup.

**Comment by kingRayhan** [comment]
Hey @Rubel-hossain 
Thanks for loving my plugin. I also thought about this feature. 
Hope That I will release `v1.0.1` tomorrow 😄

**Comment by Rubel-hossain** [comment]
Thanks And Waiting For Update Version.
