### ISSUE TITLE
How to change the progress percentage dynamically after init?

### ISSUE THREAD

**Issue by q2apro** [kingRayhan/LineProgressbar#11]
https://kingrayhan.github.io/LineProgressbar/options.html does not show an option.

And there are no callback functions?

**Comment by kingRayhan** [comment]
Can you explain your question plz?

**Comment by q2apro** [comment]
1. You initialize the script.
2. The percentage bar appears.
3. Now the percentage bar value should be changed *afterwards*.

**Comment by devenamulhaque** [comment]
We have fixed the issue. We set all of the options like progress percentage, color, animations, unit etc.
We updated our plugin's doc. You can find your solution easily

**Comment by q2apro** [comment]
How to do change the progress bar after init? I cannot find this information in the docs: https://kingrayhan.github.io/LineProgressbar/welcome.html

Nor in the readme: https://github.com/kingRayhan/LineProgressbar

Thanks :)

**Comment by devenamulhaque** [comment]
See this https://kingrayhan.github.io/LineProgressbar/data-attrs-demo.html

**Comment by q2apro** [comment]
There is no javascript code how to change the progress bar. After init.

**Comment by devenamulhaque** [comment]
> There is no javascript code how to change the progress bar. After init.

Really, there is no javascript code. We developed and tested. We are using in our projects still now

**Comment by Munoon** [comment]
Have same problem. Every 5 seconds I have new info from server and I need to update progress bar depending on that info. Is there any way to do this?

**Comment by devenamulhaque** [comment]
If you need custom option, you can contact with us. We will make plugin depending on your requirements.
electronthemes@gmail.com

**Comment by Munoon** [comment]
Add that opportunity on my own.
https://github.com/kingRayhan/LineProgressbar/pull/19
